### ISSUE TITLE
怎么运行啊 

### ISSUE THREAD

**Issue by lexang** [laure1102/lpanda#1]
怎么运行啊

**Comment by lexang** [comment]
![微信截图_20240903102222](https://github.com/user-attachments/assets/a65700be-512e-4321-9872-10b1be65b5a6)
我的不知道为啥报错了

**Comment by laure1102** [comment]
貌似electron版本问题? 你看下package.json中的electron版本, npm install有没有正确的版本。

**Comment by lexang** [comment]
> 貌似electron版本问题? 你看下package.json中的electron版本, npm install有没有正确的版本。
![image](https://github.com/user-attachments/assets/13d2fc38-b6b1-460e-925b-616c638358e6)

![image](https://github.com/user-attachments/assets/b753a344-d091-41f4-8aec-f3fbaf9d935c)
![image](https://github.com/user-attachments/assets/ccc11b0a-5f3f-465a-9c72-afd807390024)
 npm start    之后 打开http://localhost:3000/#/      控制台报错  那写下拉列表数据也没加载成功

**Comment by lexang** [comment]
main.js:14 [Vue warn]: Error in created hook: "TypeError: Cannot read properties of undefined (reading 'receiveAways')"

found in

---> <Main> at src/Main.vue
       <Root>
warn @ vue.js?v=a187f6f1:3556
logError @ vue.js?v=a187f6f1:2346
globalHandleError @ vue.js?v=a187f6f1:2342
handleError @ vue.js?v=a187f6f1:2312
invokeWithErrorHandling @ vue.js?v=a187f6f1:2328
callHook$1 @ vue.js?v=a187f6f1:3111
Vue2._init @ vue.js?v=a187f6f1:4408
VueComponent @ vue.js?v=a187f6f1:4516
createComponentInstanceForVnode @ vue.js?v=a187f6f1:3500
init @ vue.js?v=a187f6f1:3394
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
patch2 @ vue.js?v=a187f6f1:5536
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
（匿名） @ main.js:14
显示另外 19 个框架
收起
main.js:14 TypeError: Cannot read properties of undefined (reading 'receiveAways')
    at Object.ipcReceiveAways (utils.js:50:26)
    at VueComponent.created (Main.vue:27:1)
    at invokeWithErrorHandling (vue.js?v=a187f6f1:2320:57)
    at callHook$1 (vue.js?v=a187f6f1:3111:7)
    at Vue2._init (vue.js?v=a187f6f1:4408:5)
    at new VueComponent (vue.js?v=a187f6f1:4516:12)
    at createComponentInstanceForVnode (vue.js?v=a187f6f1:3500:10)
    at init (vue.js?v=a187f6f1:3394:45)
    at createComponent2 (vue.js?v=a187f6f1:5112:9)
    at createElm (vue.js?v=a187f6f1:5074:9)
logError @ vue.js?v=a187f6f1:2349
globalHandleError @ vue.js?v=a187f6f1:2342
handleError @ vue.js?v=a187f6f1:2312
invokeWithErrorHandling @ vue.js?v=a187f6f1:2328
callHook$1 @ vue.js?v=a187f6f1:3111
Vue2._init @ vue.js?v=a187f6f1:4408
VueComponent @ vue.js?v=a187f6f1:4516
createComponentInstanceForVnode @ vue.js?v=a187f6f1:3500
init @ vue.js?v=a187f6f1:3394
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
patch2 @ vue.js?v=a187f6f1:5536
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
（匿名） @ main.js:14
显示另外 18 个框架
收起
main.js:14 [Vue warn]: Error in created hook: "TypeError: Cannot read properties of undefined (reading 'send')"

found in

---> <Setting> at src/pages/Setting.vue
       <Modal>
         <Main> at src/Main.vue
           <Root>
warn @ vue.js?v=a187f6f1:3556
logError @ vue.js?v=a187f6f1:2346
globalHandleError @ vue.js?v=a187f6f1:2342
handleError @ vue.js?v=a187f6f1:2312
invokeWithErrorHandling @ vue.js?v=a187f6f1:2328
callHook$1 @ vue.js?v=a187f6f1:3111
Vue2._init @ vue.js?v=a187f6f1:4408
VueComponent @ vue.js?v=a187f6f1:4516
createComponentInstanceForVnode @ vue.js?v=a187f6f1:3500
init @ vue.js?v=a187f6f1:3394
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
patch2 @ vue.js?v=a187f6f1:5513
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
init @ vue.js?v=a187f6f1:3395
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
patch2 @ vue.js?v=a187f6f1:5513
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
init @ vue.js?v=a187f6f1:3395
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
patch2 @ vue.js?v=a187f6f1:5513
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
init @ vue.js?v=a187f6f1:3395
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
patch2 @ vue.js?v=a187f6f1:5536
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
（匿名） @ main.js:14
显示另外 61 个框架
收起
main.js:14 TypeError: Cannot read properties of undefined (reading 'send')
    at Object.ipcSend (utils.js:44:26)
    at VueComponent.initSetting (Setting.vue:266:1)
    at VueComponent.created (Setting.vue:327:1)
    at invokeWithErrorHandling (vue.js?v=a187f6f1:2320:57)
    at callHook$1 (vue.js?v=a187f6f1:3111:7)
    at Vue2._init (vue.js?v=a187f6f1:4408:5)
    at new VueComponent (vue.js?v=a187f6f1:4516:12)
    at createComponentInstanceForVnode (vue.js?v=a187f6f1:3500:10)
    at init (vue.js?v=a187f6f1:3394:45)
    at createComponent2 (vue.js?v=a187f6f1:5112:9)
logError @ vue.js?v=a187f6f1:2349
globalHandleError @ vue.js?v=a187f6f1:2342
handleError @ vue.js?v=a187f6f1:2312
invokeWithErrorHandling @ vue.js?v=a187f6f1:2328
callHook$1 @ vue.js?v=a187f6f1:3111
Vue2._init @ vue.js?v=a187f6f1:4408
VueComponent @ vue.js?v=a187f6f1:4516
createComponentInstanceForVnode @ vue.js?v=a187f6f1:3500
init @ vue.js?v=a187f6f1:3394
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
patch2 @ vue.js?v=a187f6f1:5513
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
init @ vue.js?v=a187f6f1:3395
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
patch2 @ vue.js?v=a187f6f1:5513
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
init @ vue.js?v=a187f6f1:3395
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
createChildren @ vue.js?v=a187f6f1:5170
createElm @ vue.js?v=a187f6f1:5091
patch2 @ vue.js?v=a187f6f1:5513
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
init @ vue.js?v=a187f6f1:3395
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
patch2 @ vue.js?v=a187f6f1:5536
Vue2._update @ vue.js?v=a187f6f1:2898
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2 @ vue.js?v=a187f6f1:2637
mountComponent @ vue.js?v=a187f6f1:2997
Vue.$mount @ vue.js?v=a187f6f1:6853
（匿名） @ main.js:14
显示另外 60 个框架
收起
vue.js?v=a187f6f1:6865 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
view-design.js?v=a187f6f1:6713 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
page.js:5 page.js ReaderArticleFinder {contentDocument: document, didSearchForArticleNode: false, article: null, didSearchForExtraArticleNode: false, extraArticle: null, …} Readability ƒ Readability(doc, options) {
  // In some older versions, people passed a URI as the first argument. Cope:
  if (options && options.documentElement) {
    doc = options
    options = arguments[2]
…
page.js:264 discuz_cache
page.js:309 skip
client.ts:53 [vite] connected.
main.js:11 [Vue warn]: Error in created hook: "TypeError: Cannot read properties of undefined (reading 'send')"

found in

---> <App> at src/pages/App.vue
       <Content>
         <Layout>
           <Main> at src/Main.vue
             <Root>
warn @ vue.js?v=a187f6f1:3556
logError @ vue.js?v=a187f6f1:2346
globalHandleError @ vue.js?v=a187f6f1:2342
handleError @ vue.js?v=a187f6f1:2312
invokeWithErrorHandling @ vue.js?v=a187f6f1:2328
callHook$1 @ vue.js?v=a187f6f1:3111
Vue2._init @ vue.js?v=a187f6f1:4408
VueComponent @ vue.js?v=a187f6f1:4516
createComponentInstanceForVnode @ vue.js?v=a187f6f1:3500
init @ vue.js?v=a187f6f1:3394
createComponent2 @ vue.js?v=a187f6f1:5112
createElm @ vue.js?v=a187f6f1:5074
addVnodes @ vue.js?v=a187f6f1:5213
updateChildren @ vue.js?v=a187f6f1:5326
patchVnode @ vue.js?v=a187f6f1:5388
patch2 @ vue.js?v=a187f6f1:5517
Vue2._update @ vue.js?v=a187f6f1:2900
updateComponent @ vue.js?v=a187f6f1:2979
Watcher2.get @ vue.js?v=a187f6f1:2644
Watcher2.run @ vue.js?v=a187f6f1:2698
flushSchedulerQueue @ vue.js?v=a187f6f1:3171
（匿名） @ vue.js?v=a187f6f1:2404
flushCallbacks @ vue.js?v=a187f6f1:2362
Promise.then
timerFunc @ vue.js?v=a187f6f1:2369
nextTick @ vue.js?v=a187f6f1:2414
queueWatcher @ vue.js?v=a187f6f1:3234
Watcher2.update @ vue.js?v=a187f6f1:2693
Dep2.notify @ vue.js?v=a187f6f1:479
reactiveSetter @ vue.js?v=a187f6f1:660
（匿名） @ vue-router.js?v=a187f6f1:1815
（匿名） @ vue-router.js?v=a187f6f1:1814
updateRoute @ vue-router.js?v=a187f6f1:1434
（匿名） @ vue-router.js?v=a187f6f1:1329
（匿名） @ vue-router.js?v=a187f6f1:1420
step @ vue-router.js?v=a187f6f1:1203
step @ vue-router.js?v=a187f6f1:1210
runQueue @ vue-router.js?v=a187f6f1:1214
（匿名） @ vue-router.js?v=a187f6f1:1415
step @ vue-router.js?v=a187f6f1:1203
（匿名） @ vue-router.js?v=a187f6f1:1207
（匿名） @ vue-router.js?v=a187f6f1:1401
（匿名） @ vue-router.js?v=a187f6f1:1233
（匿名） @ vue-router.js?v=a187f6f1:1296
Promise.then
（匿名） @ vue-router.js?v=a187f6f1:1252
（匿名） @ vue-router.js?v=a187f6f1:1270
（匿名） @ vue-router.js?v=a187f6f1:1269
flatMapComponents @ vue-router.js?v=a187f6f1:1268
（匿名） @ vue-router.js?v=a187f6f1:1221
iterator @ vue-router.js?v=a187f6f1:1389
step @ vue-router.js?v=a187f6f1:1206
step @ vue-router.js?v=a187f6f1:1210
runQueue @ vue-router.js?v=a187f6f1:1214
confirmTransition @ vue-router.js?v=a187f6f1:1408
transitionTo @ vue-router.js?v=a187f6f1:1328
init @ vue-router.js?v=a187f6f1:1807
beforeCreate @ vue-router.js?v=a187f6f1:421
invokeWithErrorHandling @ vue.js?v=a187f6f1:2320
callHook$1 @ vue.js?v=a187f6f1:3111
Vue2._init @ vue.js?v=a187f6f1:4404
Vue @ vue.js?v=a187f6f1:4470
（匿名） @ main.js:11
显示另外 60 个框架
收起
main.js:11 TypeError: Cannot read properties of undefined (reading 'send')
    at Object.ipcSend (utils.js:44:26)
    at VueComponent.initApp (App.js?vue&type=script&src&from=E%3A%2FpythonProject%2Flpanda%2Fsrc%2Fpages%2FApp.vue&lang.js:267:19)
    at VueComponent.created (App.js?vue&type=script&src&from=E%3A%2FpythonProject%2Flpanda%2Fsrc%2Fpages%2FApp.vue&lang.js:789:14)
    at invokeWithErrorHandling (vue.js?v=a187f6f1:2320:57)
    at callHook$1 (vue.js?v=a187f6f1:3111:7)
    at Vue2._init (vue.js?v=a187f6f1:4408:5)
    at new VueComponent (vue.js?v=a187f6f1:4516:12)
    at createComponentInstanceForVnode (vue.js?v=a187f6f1:3500:10)
    at init (vue.js?v=a187f6f1:3394:45)
    at createComponent2 (vue.js?v=a187f6f1:5112:9)

**Comment by laure1102** [comment]
这个是桌面软件，不要用浏览器访问localhost:3000
直接npm install后，npm start或者npm run start。会自动打开软件。
如果不行：请贴一下npm start后的输出，我再看下。

**Comment by lexang** [comment]
![image](https://github.com/user-attachments/assets/854f7189-5675-4011-b050-98abbba3d873)
(base) PS E:\pythonProject\lpanda> npm start    

> lpanda@1.0.1 start
> concurrently -k "npm run dev" "npm run electron"

[0]
[0] > lpanda@1.0.1 dev
[0] > vite
[0]
[1]
[1] > lpanda@1.0.1 electron
[1] > wait-on tcp:3000 &&  npm run dev:el
[1]
[0] 
[0]   vite v2.9.18 dev server running at:
[0]
[0]   > Local: http://localhost:3000/    
[0]   > Network: use `--host` to expose  
[0]
[0]   ready in 395ms.
[0]
[0] 12:33:17 [vite] warning: <Step v-for="item in stepNames">: component lists rendered with v-for should have explicit keys. See https://v2.vuejs.org/v2/guide/list.html#key for more info.
[0]   Plugin: vite-plugin-vue2
[0]   File: E:/pythonProject/lpanda/src/pages/App.vue

**Comment by lexang** [comment]
> 这个是桌面软件，不要用浏览器访问localhost:3000 直接npm install后，npm start或者npm run start。会自动打开软件。 如果不行：请贴一下npm start后的输出，我再看下。

没有打开软件

**Comment by laure1102** [comment]
你是本地用命令行运行的吗？

**Comment by lexang** [comment]
> 你是本地用命令行运行的吗？

嗯嗯 是的  在vscode的终端运行的  我看你用的vue  electron版本都比较老    会不会是我node版本太高了？

**Comment by laure1102** [comment]
有可能，你用nvm 装个node 14试试，不行你修改一下pacakge.json，去掉^，指定版本，再npm install试试

**Comment by lexang** [comment]
> 有可能，你用nvm 装个node 14试试，不行你修改一下pacakge.json，去掉^，指定版本，再npm install试试

终于出来了 。。。   应该就是node版本问题
