### ISSUE TITLE
我的 npm install有问题，一直在出错

### ISSUE THREAD

**Issue by QiuFuren** [laure1102/lpanda#4]
(venv) PS F:\student\24Hbase\AI\lpanda-main> npm install            
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'v-click-outside-x@3.7.1',
npm warn EBADENGINE   required: { node: '>=8.11.4', npm: '6.4.1' },
npm warn EBADENGINE   current: { node: 'v22.11.0', npm: '10.9.0' }
npm warn EBADENGINE }
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated consolidate@0.16.0: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm warn deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm warn deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm warn deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm warn deprecated electron-packager@17.1.2: Please use @electron/packager moving forward. There is no API change, just a package name change
npm warn deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm warn deprecated vue@2.7.16: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.
npm error code 1
npm error path F:\student\24Hbase\AI\lpanda-main\node_modules\electron
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm error RequestError: connect ETIMEDOUT 20.205.243.166:443
npm error     at ClientRequest.<anonymous> (F:\student\24Hbase\AI\lpanda-main\node_modules\got\source\request-as-event-emitter.js:178:14)
npm error     at Object.onceWrapper (node:events:633:26)
npm error     at ClientRequest.emit (node:events:530:35)
npm error     at origin.emit (F:\student\24Hbase\AI\lpanda-main\node_modules\@szmarczak\http-timer\source\index.js:37:11)
npm error     at emitErrorEvent (node:_http_client:103:11)
npm error     at TLSSocket.socketErrorListener (node:_http_client:506:5)
npm error     at TLSSocket.emit (node:events:518:28)
npm error     at emitErrorNT (node:internal/streams/destroy:170:8)
npm error     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
npm error A complete log of this run can be found in: C:\Users\86157\AppData\Local\npm-cache\_logs\2024-11-04T07_27_37_491Z-debug-0.log
(venv) PS F:\student\24Hbase\AI\lpanda-main> npm install electron
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'v-click-outside-x@3.7.1',
npm warn EBADENGINE   required: { node: '>=8.11.4', npm: '6.4.1' },
npm warn EBADENGINE   current: { node: 'v22.11.0', npm: '10.9.0' }
npm warn EBADENGINE }
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated consolidate@0.16.0: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm warn deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm warn deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm warn deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm warn deprecated electron-packager@17.1.2: Please use @electron/packager moving forward. There is no API change, just a package name change
npm warn deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm warn deprecated vue@2.7.16: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.
npm error code 1
npm error path F:\student\24Hbase\AI\lpanda-main\node_modules\electron
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm error RequestError: socket hang up
npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm warn deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm warn deprecated vue@2.7.16: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.
-
(venv) PS F:\student\24Hbase\AI\lpanda-main> ^C
(venv) PS F:\student\24Hbase\AI\lpanda-main> npm cache clean --force
我看不明白这是为什么，搜索的办法也不能解决

**Comment by QiuFuren** [comment]
希望您能看见我，出现了一个新的问题
<img width="404" alt="a12ffdf48de3ac08b6ab19de48f0bac" src="https://github.com/user-attachments/assets/47ebc7a4-8cca-47c9-b6d4-9b73e2673116">

**Comment by laure1102** [comment]
我看到你使用的node是22版本，请使用14版本试试

**Comment by QiuFuren** [comment]
<img width="669" alt="826c549bd0ebd877eeff3a419b46188" src="https://github.com/user-attachments/assets/e7939e99-e161-4cee-bb94-4af6c910a2cc">

**Comment by QiuFuren** [comment]
app页面出现以后，需要进入设置进行修改吗？

**Comment by QiuFuren** [comment]
<img width="917" alt="155f16c3e0699bb58906ca5b0462270" src="https://github.com/user-attachments/assets/d9b48794-a8b6-4da2-8141-0f62a76ce94a">
我这里无法处理文件
